services:
  web:
    image: nginx:1.27-alpine
    container_name: lab9_nginx
    ports:
      - "8090:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab9_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab9_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab9_db
      MYSQL_USER: lab9_user
      MYSQL_PASSWORD: lab9_pass
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data: